import bcrypt from 'bcryptjs'
import pool from '../config/db.js'
import { MIN_PASSWORD_LENGTH } from '../config/auth.js'
import { ERROR_CODES, errorBody } from '../utils/errorCodes.js'

// Accept #rgb / #rrggbb / #rrggbbaa (normalised lowercase); anything else → null.
function normalizeHexColor(value) {
  if (!value) return null
  const hex = String(value).trim().toLowerCase()
  return /^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/.test(hex) ? hex : null
}

function normalizeText(value, maxLength) {
  const text = String(value ?? '').trim()
  return text ? text.slice(0, maxLength) : null
}

function mapAppearance(row) {
  return {
    accentColor: row.accent_color ?? null,
    accentShadow: row.accent_shadow ?? null,
    publicBrandLogo: row.public_brand_logo ?? null,
    publicPoweredByText: row.public_powered_by_text ?? null,
    publicBrandName: row.public_brand_name ?? null,
    publicPoweredByColor: row.public_powered_by_color ?? null,
    publicBrandNameColor: row.public_brand_name_color ?? null,
  }
}

// GET /api/admin/appearance — the Super Admin's own dashboard colours.
// SELECT * so a not-yet-migrated column can't crash the read.
export async function getAppearance(req, res, next) {
  try {
    const [rows] = await pool.query('SELECT * FROM admins WHERE id = ?', [req.admin.id])
    const row = rows[0] || {}
    res.json(mapAppearance(row))
  } catch (err) {
    next(err)
  }
}

// PATCH /api/admin/appearance — update the colours (guarded so a missing column
// is skipped rather than crashing, mirroring the merchant profile pattern).
export async function updateAppearance(req, res, next) {
  try {
    const body = req.body ?? {}

    const [colRows] = await pool.query(
      `SELECT column_name AS name FROM information_schema.columns
       WHERE table_schema = DATABASE() AND table_name = 'admins'`,
    )
    const existing = new Set(colRows.map((c) => c.name))

    const map = {
      accentColor: 'accent_color',
      accentShadow: 'accent_shadow',
      publicBrandLogo: 'public_brand_logo',
      publicPoweredByText: 'public_powered_by_text',
      publicBrandName: 'public_brand_name',
      publicPoweredByColor: 'public_powered_by_color',
      publicBrandNameColor: 'public_brand_name_color',
    }
    const HEX_FIELDS = new Set(['accentColor', 'accentShadow', 'publicPoweredByColor', 'publicBrandNameColor'])
    const assignments = []
    const values = []
    for (const [field, column] of Object.entries(map)) {
      if (!Object.prototype.hasOwnProperty.call(body, field)) continue
      if (!existing.has(column)) continue
      assignments.push(`${column} = ?`)
      if (HEX_FIELDS.has(field)) {
        values.push(normalizeHexColor(body[field]))
      } else if (field === 'publicBrandLogo') {
        values.push(body[field] || null)
      } else if (field === 'publicPoweredByText') {
        values.push(normalizeText(body[field], 80))
      } else {
        values.push(normalizeText(body[field], 120))
      }
    }

    if (assignments.length) {
      values.push(req.admin.id)
      await pool.query(`UPDATE admins SET ${assignments.join(', ')} WHERE id = ?`, values)
    }

    const [rows] = await pool.query('SELECT * FROM admins WHERE id = ?', [req.admin.id])
    const row = rows[0] || {}
    res.json(mapAppearance(row))
  } catch (err) {
    next(err)
  }
}

/**
 * POST /api/admin/change-password  { currentPassword, newPassword }
 *
 * The Super Admin had no way to change their own password. The bootstrap
 * account was seeded with a constant committed to the repo, and nothing in the
 * API or the UI could replace it — the only route was raw SQL and a bcrypt
 * hash generated by hand.
 *
 * MOUNTING MATTERS HERE. This must be registered on adminProfileRouter, which
 * app.js mounts behind requireAdmin. /api/admin is mounted twice: the
 * unauthenticated adminAuthRouter (login/logout) is first, and any path IT
 * defines wins. Putting this handler there would expose an unauthenticated
 * password change for any admin account.
 *
 * Knowing the current password is required even though the caller is already
 * authenticated: it is what stops a borrowed unlocked laptop from becoming a
 * permanent account takeover.
 */
export async function changeAdminPassword(req, res, next) {
  try {
    const { currentPassword, newPassword } = req.body ?? {}

    if (typeof newPassword !== 'string' || newPassword.length < MIN_PASSWORD_LENGTH) {
      return res.status(400).json(
        errorBody(
          `Password must be at least ${MIN_PASSWORD_LENGTH} characters`,
          ERROR_CODES.WEAK_PASSWORD,
          { min: MIN_PASSWORD_LENGTH },
        ),
      )
    }

    const [rows] = await pool.query('SELECT password_hash FROM admins WHERE id = ?', [
      req.admin.id,
    ])
    if (!rows.length) {
      return res.status(404).json({ status: 'error', error: 'Admin not found' })
    }

    const ok =
      typeof currentPassword === 'string' &&
      rows[0].password_hash &&
      (await bcrypt.compare(currentPassword, rows[0].password_hash))
    if (!ok) {
      return res
        .status(403)
        .json(errorBody('Your current password is not correct.', ERROR_CODES.CURRENT_PASSWORD_WRONG))
    }

    await pool.query('UPDATE admins SET password_hash = ? WHERE id = ?', [
      await bcrypt.hash(newPassword, 10),
      req.admin.id,
    ])

    // Note: sessions on other devices stay valid. Invalidating them needs a
    // token_version column checked on every request; requireAdmin currently
    // makes no database call at all. Documented in backend/README.md.
    res.json({ ok: true })
  } catch (err) {
    next(err)
  }
}
